kubectl delete deploy iviaruntime
kubectl delete deploy iviawrprp1
kubectl delete deploy iviaconfig
kubectl delete deploy openldap
kubectl delete deploy postgresql
kubectl delete deploy iviadsc
kubectl delete service iviaconfig
kubectl delete service iviaruntime
kubectl delete service iviawrprp1
kubectl delete service openldap
kubectl delete service postgresql
kubectl delete service iviadsc
kubectl delete ingress iviawrprp1
kubectl delete service isvaop
kubectl delete secret configreader
kubectl delete secret iviaadmin
kubectl delete secret dockerlogin
kubectl delete secret openldap-keys
kubectl delete secret postgresql-keys
kubectl delete pvc iviaconfig
kubectl delete pvc ldaplib
kubectl delete pvc ldapsecauthority
kubectl delete pvc ldapslapd
kubectl delete pvc postgresqldata
