kubectl delete deploy isvaruntime
kubectl delete deploy isvawrprp1
kubectl delete deploy isvaconfig
kubectl delete deploy openldap
kubectl delete deploy postgresql
kubectl delete deploy isvadsc
kubectl delete service isvaconfig
kubectl delete service isvaruntime
kubectl delete service isvawrprp1
kubectl delete service openldap
kubectl delete service postgresql
kubectl delete service isvadsc
kubectl delete ingress isvawrprp1
kubectl delete secret configreader
kubectl delete secret isvaadmin
kubectl delete secret dockerlogin
kubectl delete secret openldap-keys
kubectl delete secret postgresql-keys
kubectl delete pvc isvaconfig
kubectl delete pvc ldaplib
kubectl delete pvc ldapsecauthority
kubectl delete pvc ldapslapd
kubectl delete pvc postgresqldata
